version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - unzip '*.zip' | for i in *.py; do python $i & done
     - aws s3 sync --debug --delete . s3://web-pipeline
 post_build:
   commands:
     - echo "post_build step"
